language: node_js
node_js:
  - 'stable'
  - '0.12'
env:
before_script:
  - npm install -g cnpm
  - cnpm -v
script:
  - npm run lint
  - cd test
  - cnpm install && npm test
  - rm -rf node_modules
  - cnpm install && npm test
