language: node_js
node_js:
  - stable
  - "5.0"
  - "4.0"
  - "0.12"
env:
before_script:
  - npm install -g gulp
  - gulp -v
script:
  - npm run lint
  - npm run build

  - rm -rf node_modules

  - cd examples
  - npm install
  - npm test
  - gulp build
  - gulp build --p
