language: node_js
node_js:
  - 'stable'
  - '0.12'
env:
before_script:
  - npm install -g cnpm gulp
  - cnpm -v
script:
  - npm run lint
  - cd examples
  - npm install
  - npm test
  - gulp build
  - gulp build --p
  - rm -rf node_modules
